export const GET_LOGIN_REQUEST='GET_LOGIN_REQUEST'
export const GET_LOGIN_SUCCESS='GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAIL='GET_LOGIN_FAIL'

export const GET_REGISTER_REQUEST='GET_REGISTER_REQUEST'
export const GET_REGISTER_SUCCESS='GET_REGISTER_SUCCESS'
export const GET_REGISTER_FAIL='GET_REGISTER_FAIL'

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'