export const GET_REQUEST_CATEGORY='GET_REQUEST_CATEGORY'
export const GET_SUCCESS_CATEGORY='GET_SUCCESS_CATEGORY'
export const GET_FAIL_CATEGORY='GET_FAIL_CATEGORY'

export const ADD_REQUEST_CATEGORY='ADD_REQUEST_CATEGORY'
export const ADD_SUCCESS_CATEGORY='ADD_SUCCESS_CATEGORY'
export const ADD_FAIL_CATEGORY='ADD_FAIL_CATEGORY'

export const ADD_REQUEST_SUB_CATEGORY='ADD_REQUEST_SUB_CATEGORY'
export const ADD_SUCCESS_SUB_CATEGORY='ADD_SUCCESS_SUB_CATEGORY'
export const ADD_FAIL_SUB_CATEGORY='ADD_FAIL_SUB_CATEGORY'

export const DELETE_REQUEST_CATEGORY='DELETE_REQUEST_CATEGORY'
export const DELETE_SUCCESS_CATEGORY='DELETE_SUCCESS_CATEGORY'
export const DELETE_FAIL_CATEGORY='DELETE_FAIL_CATEGORY'

export const DELETE_REQUEST_SUB_CATEGORY='DELETE_REQUEST_SUB_CATEGORY'
export const DELETE_SUCCESS_SUB_CATEGORY='DELETE_SUCCESS_SUB_CATEGORY'
export const DELETE_FAIL_SUB_CATEGORY='DELETE_FAIL_SUB_CATEGORY'