export const GET_REQUEST_PROFILE='GET_REQUEST_PROFILE'
export const GET_SUCCESS_PROFILE='GET_SUCCESS_PROFILE'
export const GET_FAIL_PROFILE='GET_FAIL_PROFILE'

export const UPDATE_REQUEST_PROFILE='UPDATE_REQUEST_PROFILE'
export const UPDATE_SUCCESS_PROFILE='UPDATE_SUCCESS_PROFILE'
export const UPDATE_FAIL_PROFILE='UPDATE_FAIL_PROFILE'