# Generated by Django 4.0.3 on 2022-03-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
