# Generated by Django 4.0.3 on 2022-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_contact_neighborhood_sub_category_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
